version: "3.9"

services:

  db:
    image: postgres:15
    container_name: hotel-db
    restart: always
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_app
      POSTGRES_PASSWORD: hotel_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  tomcat:
    build: .
    container_name: hotel-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/hotel_db
      DB_USER: hotel_app
      DB_PASSWORD: hotel_password

volumes:
  postgres-data: